# -*- buffer-read-only: t -*- vi: set ro:
# DO NOT EDIT! GENERATED AUTOMATICALLY!
# DO NOT EDIT! GENERATED AUTOMATICALLY!
# Copyright (C) 2002-2011 Free Software Foundation, Inc.
#
# This file is free software, distributed under the terms of the GNU
# General Public License.  As a special exception to the GNU General
# Public License, this file may be distributed as part of a program
# that contains a configuration script generated by Autoconf, under
# the same distribution terms as the rest of that program.
#
# Generated by gnulib-tool.
#
# This file represents the compiled summary of the specification in
# gnulib-cache.m4. It lists the computed macro invocations that need
# to be invoked from configure.ac.
# In projects that use version control, this file can be treated like
# other built files.


# This macro should be invoked from ./configure.ac, in the section
# "Checks for programs", right after AC_PROG_CC, and certainly before
# any checks for libraries, header files, types and library functions.
AC_DEFUN([gl_EARLY],
[
  m4_pattern_forbid([^gl_[A-Z]])dnl the gnulib macro namespace
  m4_pattern_allow([^gl_ES$])dnl a valid locale name
  m4_pattern_allow([^gl_LIBOBJS$])dnl a variable
  m4_pattern_allow([^gl_LTLIBOBJS$])dnl a variable
  AC_REQUIRE([AC_PROG_RANLIB])
  AC_REQUIRE([AM_PROG_CC_C_O])
  # Code from module accept:
  # Code from module alignof:
  # Code from module alignof-tests:
  # Code from module alloca:
  # Code from module alloca-opt:
  # Code from module alloca-opt-tests:
  # Code from module areadlink:
  # Code from module areadlink-tests:
  # Code from module arg-nonnull:
  # Code from module arpa_inet:
  # Code from module arpa_inet-tests:
  # Code from module base64:
  # Code from module base64-tests:
  # Code from module binary-io:
  # Code from module binary-io-tests:
  # Code from module bind:
  # Code from module c++defs:
  # Code from module c-ctype:
  # Code from module c-ctype-tests:
  # Code from module canonicalize-lgpl:
  # Code from module canonicalize-lgpl-tests:
  # Code from module chown:
  # Code from module chown-tests:
  # Code from module close:
  # Code from module close-hook:
  # Code from module configmake:
  # Code from module connect:
  # Code from module count-one-bits:
  # Code from module count-one-bits-tests:
  # Code from module crypto/md5:
  # Code from module crypto/md5-tests:
  # Code from module dirname-lgpl:
  # Code from module double-slash-root:
  # Code from module environ:
  # Code from module environ-tests:
  # Code from module errno:
  # Code from module errno-tests:
  # Code from module error:
  # Code from module exitfail:
  # Code from module extensions:
  AC_REQUIRE([gl_USE_SYSTEM_EXTENSIONS])
  # Code from module fclose:
  # Code from module fcntl-h:
  # Code from module fcntl-h-tests:
  # Code from module float:
  # Code from module fseeko:
  AC_REQUIRE([AC_FUNC_FSEEKO])
  # Code from module fseeko-tests:
  # Code from module func:
  # Code from module func-tests:
  # Code from module getaddrinfo:
  # Code from module getaddrinfo-tests:
  # Code from module getdelim:
  # Code from module getdelim-tests:
  # Code from module getgroups:
  # Code from module getgroups-tests:
  # Code from module gethostname:
  # Code from module gethostname-tests:
  # Code from module getline:
  # Code from module getline-tests:
  # Code from module getpagesize:
  # Code from module getpass:
  # Code from module gettext-h:
  # Code from module gettimeofday:
  # Code from module gettimeofday-tests:
  # Code from module getugroups:
  # Code from module gitlog-to-changelog:
  # Code from module gnumakefile:
  # Code from module havelib:
  # Code from module hostent:
  # Code from module ignore-value:
  # Code from module ignore-value-tests:
  # Code from module include_next:
  # Code from module inet_ntop:
  # Code from module inet_ntop-tests:
  # Code from module inet_pton:
  # Code from module inet_pton-tests:
  # Code from module inline:
  # Code from module intprops:
  # Code from module ioctl:
  # Code from module listen:
  # Code from module lock:
  # Code from module lock-tests:
  # Code from module lseek:
  # Code from module lseek-tests:
  # Code from module lstat:
  # Code from module lstat-tests:
  # Code from module maintainer-makefile:
  # Code from module malloc-posix:
  # Code from module malloca:
  # Code from module malloca-tests:
  # Code from module memchr:
  # Code from module memchr-tests:
  # Code from module mgetgroups:
  # Code from module mkstemp:
  # Code from module mkstemps:
  # Code from module mktempd:
  # Code from module mktime:
  # Code from module multiarch:
  # Code from module netdb:
  # Code from module netdb-tests:
  # Code from module netinet_in:
  # Code from module netinet_in-tests:
  # Code from module open:
  # Code from module open-tests:
  # Code from module pathmax:
  # Code from module perror:
  # Code from module perror-tests:
  # Code from module physmem:
  # Code from module pipe-posix:
  # Code from module pipe-posix-tests:
  # Code from module poll:
  # Code from module poll-h:
  # Code from module poll-h-tests:
  # Code from module poll-tests:
  # Code from module posix-shell:
  # Code from module progname:
  # Code from module pthread:
  # Code from module putenv:
  # Code from module random_r:
  # Code from module random_r-tests:
  # Code from module rawmemchr:
  # Code from module rawmemchr-tests:
  # Code from module readlink:
  # Code from module readlink-tests:
  # Code from module realloc-gnu:
  # Code from module realloc-gnu-tests:
  # Code from module realloc-posix:
  # Code from module recv:
  # Code from module same-inode:
  # Code from module sched:
  # Code from module sched-tests:
  # Code from module select:
  # Code from module select-tests:
  # Code from module send:
  # Code from module servent:
  # Code from module setsockopt:
  # Code from module sigaction:
  # Code from module sigaction-tests:
  # Code from module signal:
  # Code from module signal-tests:
  # Code from module sigpipe:
  # Code from module sigpipe-tests:
  # Code from module sigprocmask:
  # Code from module size_max:
  # Code from module sleep:
  # Code from module sleep-tests:
  # Code from module snprintf:
  # Code from module snprintf-tests:
  # Code from module socket:
  # Code from module socketlib:
  # Code from module sockets:
  # Code from module sockets-tests:
  # Code from module socklen:
  # Code from module ssize_t:
  # Code from module stat:
  # Code from module stat-tests:
  # Code from module stat-time:
  # Code from module stat-time-tests:
  # Code from module stdbool:
  # Code from module stdbool-tests:
  # Code from module stddef:
  # Code from module stddef-tests:
  # Code from module stdint:
  # Code from module stdint-tests:
  # Code from module stdio:
  # Code from module stdio-tests:
  # Code from module stdlib:
  # Code from module stdlib-tests:
  # Code from module stpcpy:
  # Code from module strcase:
  # Code from module strchrnul:
  # Code from module strchrnul-tests:
  # Code from module strdup-posix:
  # Code from module strerror:
  # Code from module strerror-tests:
  # Code from module strerror_r-posix:
  # Code from module strerror_r-posix-tests:
  # Code from module string:
  # Code from module string-tests:
  # Code from module strings:
  # Code from module strings-tests:
  # Code from module strndup:
  # Code from module strnlen:
  # Code from module strnlen-tests:
  # Code from module strptime:
  # Code from module strsep:
  # Code from module strtok_r:
  # Code from module symlink:
  # Code from module symlink-tests:
  # Code from module sys_ioctl:
  # Code from module sys_ioctl-tests:
  # Code from module sys_select:
  # Code from module sys_select-tests:
  # Code from module sys_socket:
  # Code from module sys_socket-tests:
  # Code from module sys_stat:
  # Code from module sys_stat-tests:
  # Code from module sys_time:
  # Code from module sys_time-tests:
  # Code from module sys_utsname:
  # Code from module sys_utsname-tests:
  # Code from module sys_wait:
  # Code from module sys_wait-tests:
  # Code from module tempname:
  # Code from module termios:
  # Code from module termios-tests:
  # Code from module thread:
  # Code from module threadlib:
  gl_THREADLIB_EARLY
  # Code from module time:
  # Code from module time-tests:
  # Code from module time_r:
  # Code from module timegm:
  # Code from module uname:
  # Code from module uname-tests:
  # Code from module unistd:
  # Code from module unistd-tests:
  # Code from module unsetenv:
  # Code from module unsetenv-tests:
  # Code from module useless-if-before-free:
  # Code from module usleep:
  # Code from module usleep-tests:
  # Code from module vasnprintf:
  # Code from module vasnprintf-tests:
  # Code from module vasprintf:
  # Code from module vasprintf-tests:
  # Code from module vc-list-files:
  # Code from module vc-list-files-tests:
  # Code from module verify:
  # Code from module verify-tests:
  # Code from module waitpid:
  # Code from module warn-on-use:
  # Code from module wchar:
  # Code from module wchar-tests:
  # Code from module write:
  # Code from module xalloc:
  # Code from module xalloc-die:
  # Code from module xalloc-die-tests:
  # Code from module xsize:
  # Code from module yield:
])

# This macro should be invoked from ./configure.ac, in the section
# "Check for header files, types and library functions".
AC_DEFUN([gl_INIT],
[
  AM_CONDITIONAL([GL_COND_LIBTOOL], [true])
  gl_cond_libtool=true
  gl_m4_base='gnulib/m4'
  m4_pushdef([AC_LIBOBJ], m4_defn([gl_LIBOBJ]))
  m4_pushdef([AC_REPLACE_FUNCS], m4_defn([gl_REPLACE_FUNCS]))
  m4_pushdef([AC_LIBSOURCES], m4_defn([gl_LIBSOURCES]))
  m4_pushdef([gl_LIBSOURCES_LIST], [])
  m4_pushdef([gl_LIBSOURCES_DIR], [])
  gl_COMMON
  gl_source_base='gnulib/lib'
  # Code from module alignof:
  # Code from module alloca:
changequote(,)dnl
LTALLOCA=`echo "$ALLOCA" | sed -e 's/\.[^.]* /.lo /g;s/\.[^.]*$/.lo/'`
changequote([, ])dnl
AC_SUBST([LTALLOCA])
  # Code from module alloca-opt:
  gl_FUNC_ALLOCA
  # Code from module areadlink:
  # Code from module arg-nonnull:
  # Code from module arpa_inet:
  gl_HEADER_ARPA_INET
  AC_PROG_MKDIR_P
  # Code from module base64:
  gl_FUNC_BASE64
  # Code from module c++defs:
  # Code from module c-ctype:
  # Code from module canonicalize-lgpl:
  gl_CANONICALIZE_LGPL
  gl_MODULE_INDICATOR([canonicalize-lgpl])
  gl_STDLIB_MODULE_INDICATOR([canonicalize_file_name])
  gl_STDLIB_MODULE_INDICATOR([realpath])
  # Code from module chown:
  gl_FUNC_CHOWN
  gl_UNISTD_MODULE_INDICATOR([chown])
  # Code from module close:
  gl_FUNC_CLOSE
  gl_UNISTD_MODULE_INDICATOR([close])
  # Code from module close-hook:
  # Code from module configmake:
  gl_CONFIGMAKE_PREP
  # Code from module connect:
  AC_REQUIRE([gl_HEADER_SYS_SOCKET])
  if test "$ac_cv_header_winsock2_h" = yes; then
    AC_LIBOBJ([connect])
  fi
  gl_SYS_SOCKET_MODULE_INDICATOR([connect])
  # Code from module count-one-bits:
  gl_COUNT_ONE_BITS
  # Code from module crypto/md5:
  gl_MD5
  # Code from module dirname-lgpl:
  gl_DIRNAME_LGPL
  # Code from module double-slash-root:
  gl_DOUBLE_SLASH_ROOT
  # Code from module errno:
  gl_HEADER_ERRNO_H
  # Code from module extensions:
  # Code from module fclose:
  gl_FUNC_FCLOSE
  gl_STDIO_MODULE_INDICATOR([fclose])
  # Code from module fcntl-h:
  gl_FCNTL_H
  # Code from module float:
  gl_FLOAT_H
  # Code from module fseeko:
  gl_FUNC_FSEEKO
  gl_STDIO_MODULE_INDICATOR([fseeko])
  # Code from module func:
  gl_FUNC
  # Code from module getaddrinfo:
  gl_GETADDRINFO
  gl_NETDB_MODULE_INDICATOR([getaddrinfo])
  # Code from module getdelim:
  gl_FUNC_GETDELIM
  gl_STDIO_MODULE_INDICATOR([getdelim])
  # Code from module gethostname:
  gl_FUNC_GETHOSTNAME
  gl_UNISTD_MODULE_INDICATOR([gethostname])
  # Code from module getline:
  gl_FUNC_GETLINE
  gl_STDIO_MODULE_INDICATOR([getline])
  # Code from module getpass:
  gl_FUNC_GETPASS
  # Code from module gettext-h:
  AC_SUBST([LIBINTL])
  AC_SUBST([LTLIBINTL])
  # Code from module gettimeofday:
  gl_FUNC_GETTIMEOFDAY
  gl_SYS_TIME_MODULE_INDICATOR([gettimeofday])
  # Code from module gitlog-to-changelog:
  # Code from module gnumakefile:
  # Autoconf 2.61a.99 and earlier don't support linking a file only
  # in VPATH builds.  But since GNUmakefile is for maintainer use
  # only, it does not matter if we skip the link with older autoconf.
  # Automake 1.10.1 and earlier try to remove GNUmakefile in non-VPATH
  # builds, so use a shell variable to bypass this.
  GNUmakefile=GNUmakefile
  m4_if(m4_version_compare([2.61a.100],
  	m4_defn([m4_PACKAGE_VERSION])), [1], [],
        [AC_CONFIG_LINKS([$GNUmakefile:$GNUmakefile], [],
  	[GNUmakefile=$GNUmakefile])])
  # Code from module havelib:
  # Code from module hostent:
  gl_HOSTENT
  # Code from module ignore-value:
  AC_REQUIRE([AC_C_INLINE])
  # Code from module include_next:
  # Code from module inet_ntop:
  gl_FUNC_INET_NTOP
  gl_ARPA_INET_MODULE_INDICATOR([inet_ntop])
  # Code from module inet_pton:
  gl_FUNC_INET_PTON
  gl_ARPA_INET_MODULE_INDICATOR([inet_pton])
  # Code from module intprops:
  # Code from module ioctl:
  gl_FUNC_IOCTL
  gl_SYS_IOCTL_MODULE_INDICATOR([ioctl])
  # Code from module lock:
  gl_LOCK
  # Code from module lseek:
  gl_FUNC_LSEEK
  gl_UNISTD_MODULE_INDICATOR([lseek])
  # Code from module lstat:
  gl_FUNC_LSTAT
  gl_SYS_STAT_MODULE_INDICATOR([lstat])
  # Code from module maintainer-makefile:
  AC_CONFIG_COMMANDS_PRE([m4_ifdef([AH_HEADER],
    [AC_SUBST([CONFIG_INCLUDE], m4_defn([AH_HEADER]))])])
  # Code from module malloc-posix:
  gl_FUNC_MALLOC_POSIX
  gl_STDLIB_MODULE_INDICATOR([malloc-posix])
  # Code from module malloca:
  gl_MALLOCA
  # Code from module memchr:
  gl_FUNC_MEMCHR
  gl_STRING_MODULE_INDICATOR([memchr])
  # Code from module mkstemp:
  gl_FUNC_MKSTEMP
  gl_STDLIB_MODULE_INDICATOR([mkstemp])
  # Code from module mkstemps:
  gl_FUNC_MKSTEMPS
  gl_MODULE_INDICATOR([mkstemps])
  gl_STDLIB_MODULE_INDICATOR([mkstemps])
  # Code from module mktempd:
  # Code from module mktime:
  gl_FUNC_MKTIME
  gl_TIME_MODULE_INDICATOR([mktime])
  # Code from module multiarch:
  gl_MULTIARCH
  # Code from module netdb:
  gl_HEADER_NETDB
  # Code from module netinet_in:
  gl_HEADER_NETINET_IN
  AC_PROG_MKDIR_P
  # Code from module open:
  gl_FUNC_OPEN
  gl_FCNTL_MODULE_INDICATOR([open])
  # Code from module pathmax:
  gl_PATHMAX
  # Code from module perror:
  gl_FUNC_PERROR
  gl_STRING_MODULE_INDICATOR([perror])
  # Code from module physmem:
  gl_PHYSMEM
  # Code from module pipe-posix:
  gl_FUNC_PIPE
  gl_UNISTD_MODULE_INDICATOR([pipe])
  # Code from module poll:
  gl_FUNC_POLL
  gl_POLL_MODULE_INDICATOR([poll])
  # Code from module poll-h:
  gl_POLL_H
  # Code from module posix-shell:
  gl_POSIX_SHELL
  # Code from module pthread:
  gl_PTHREAD_CHECK
  # Code from module random_r:
  gl_FUNC_RANDOM_R
  gl_STDLIB_MODULE_INDICATOR([random_r])
  # Code from module rawmemchr:
  gl_FUNC_RAWMEMCHR
  gl_STRING_MODULE_INDICATOR([rawmemchr])
  # Code from module readlink:
  gl_FUNC_READLINK
  gl_UNISTD_MODULE_INDICATOR([readlink])
  # Code from module realloc-posix:
  gl_FUNC_REALLOC_POSIX
  gl_STDLIB_MODULE_INDICATOR([realloc-posix])
  # Code from module recv:
  AC_REQUIRE([gl_HEADER_SYS_SOCKET])
  if test "$ac_cv_header_winsock2_h" = yes; then
    AC_LIBOBJ([recv])
  fi
  gl_SYS_SOCKET_MODULE_INDICATOR([recv])
  # Code from module sched:
  gl_SCHED_H
  # Code from module select:
  gl_FUNC_SELECT
  gl_SYS_SELECT_MODULE_INDICATOR([select])
  # Code from module send:
  AC_REQUIRE([gl_HEADER_SYS_SOCKET])
  if test "$ac_cv_header_winsock2_h" = yes; then
    AC_LIBOBJ([send])
  fi
  gl_SYS_SOCKET_MODULE_INDICATOR([send])
  # Code from module servent:
  gl_SERVENT
  # Code from module setsockopt:
  AC_REQUIRE([gl_HEADER_SYS_SOCKET])
  if test "$ac_cv_header_winsock2_h" = yes; then
    AC_LIBOBJ([setsockopt])
  fi
  gl_SYS_SOCKET_MODULE_INDICATOR([setsockopt])
  # Code from module sigaction:
  gl_SIGACTION
  gl_SIGNAL_MODULE_INDICATOR([sigaction])
  # Code from module signal:
  gl_SIGNAL_H
  # Code from module sigpipe:
  gl_SIGNAL_SIGPIPE
  dnl Define the C macro GNULIB_SIGPIPE to 1.
  gl_MODULE_INDICATOR([sigpipe])
  dnl Define the substituted variable GNULIB_SIGNAL_H_SIGPIPE to 1.
  AC_REQUIRE([gl_SIGNAL_H_DEFAULTS])
  GNULIB_SIGNAL_H_SIGPIPE=1
  dnl Define the substituted variable GNULIB_STDIO_H_SIGPIPE to 1.
  AC_REQUIRE([gl_STDIO_H_DEFAULTS])
  GNULIB_STDIO_H_SIGPIPE=1
  dnl Define the substituted variable GNULIB_UNISTD_H_SIGPIPE to 1.
  AC_REQUIRE([gl_UNISTD_H_DEFAULTS])
  GNULIB_UNISTD_H_SIGPIPE=1
  # Code from module sigprocmask:
  gl_SIGNALBLOCKING
  gl_SIGNAL_MODULE_INDICATOR([sigprocmask])
  # Code from module size_max:
  gl_SIZE_MAX
  # Code from module sleep:
  gl_FUNC_SLEEP
  gl_UNISTD_MODULE_INDICATOR([sleep])
  # Code from module snprintf:
  gl_FUNC_SNPRINTF
  gl_STDIO_MODULE_INDICATOR([snprintf])
  gl_MODULE_INDICATOR([snprintf])
  # Code from module socket:
  AC_REQUIRE([gl_HEADER_SYS_SOCKET])
  if test "$ac_cv_header_winsock2_h" = yes; then
    AC_LIBOBJ([socket])
  fi
  # When this module is used, sockets may actually occur as file descriptors,
  # hence it is worth warning if the modules 'close' and 'ioctl' are not used.
  m4_ifdef([gl_UNISTD_H_DEFAULTS], [AC_REQUIRE([gl_UNISTD_H_DEFAULTS])])
  m4_ifdef([gl_SYS_IOCTL_H_DEFAULTS], [AC_REQUIRE([gl_SYS_IOCTL_H_DEFAULTS])])
  AC_REQUIRE([gl_PREREQ_SYS_H_WINSOCK2])
  if test "$ac_cv_header_winsock2_h" = yes; then
    UNISTD_H_HAVE_WINSOCK2_H_AND_USE_SOCKETS=1
    SYS_IOCTL_H_HAVE_WINSOCK2_H_AND_USE_SOCKETS=1
  fi
  gl_SYS_SOCKET_MODULE_INDICATOR([socket])
  # Code from module socketlib:
  gl_SOCKETLIB
  # Code from module sockets:
  gl_SOCKETS
  # Code from module socklen:
  gl_TYPE_SOCKLEN_T
  # Code from module ssize_t:
  gt_TYPE_SSIZE_T
  # Code from module stat:
  gl_FUNC_STAT
  gl_SYS_STAT_MODULE_INDICATOR([stat])
  # Code from module stdbool:
  AM_STDBOOL_H
  # Code from module stddef:
  gl_STDDEF_H
  # Code from module stdint:
  gl_STDINT_H
  # Code from module stdio:
  gl_STDIO_H
  # Code from module stdlib:
  gl_STDLIB_H
  # Code from module stpcpy:
  gl_FUNC_STPCPY
  gl_STRING_MODULE_INDICATOR([stpcpy])
  # Code from module strcase:
  gl_STRCASE
  # Code from module strchrnul:
  gl_FUNC_STRCHRNUL
  gl_STRING_MODULE_INDICATOR([strchrnul])
  # Code from module strdup-posix:
  gl_FUNC_STRDUP_POSIX
  gl_STRING_MODULE_INDICATOR([strdup])
  # Code from module strerror:
  gl_FUNC_STRERROR
  gl_STRING_MODULE_INDICATOR([strerror])
  # Code from module strerror_r-posix:
  gl_FUNC_STRERROR_R
  gl_STRING_MODULE_INDICATOR([strerror_r])
  # Code from module string:
  gl_HEADER_STRING_H
  # Code from module strings:
  gl_HEADER_STRINGS_H
  # Code from module strndup:
  gl_FUNC_STRNDUP
  gl_STRING_MODULE_INDICATOR([strndup])
  # Code from module strnlen:
  gl_FUNC_STRNLEN
  gl_STRING_MODULE_INDICATOR([strnlen])
  # Code from module strptime:
  gl_FUNC_STRPTIME
  gl_TIME_MODULE_INDICATOR([strptime])
  # Code from module strsep:
  gl_FUNC_STRSEP
  gl_STRING_MODULE_INDICATOR([strsep])
  # Code from module strtok_r:
  gl_FUNC_STRTOK_R
  gl_STRING_MODULE_INDICATOR([strtok_r])
  # Code from module sys_ioctl:
  gl_SYS_IOCTL_H
  AC_PROG_MKDIR_P
  # Code from module sys_select:
  gl_HEADER_SYS_SELECT
  AC_PROG_MKDIR_P
  # Code from module sys_socket:
  gl_HEADER_SYS_SOCKET
  AC_PROG_MKDIR_P
  # Code from module sys_stat:
  gl_HEADER_SYS_STAT_H
  AC_PROG_MKDIR_P
  # Code from module sys_time:
  gl_HEADER_SYS_TIME_H
  AC_PROG_MKDIR_P
  # Code from module sys_utsname:
  gl_SYS_UTSNAME_H
  AC_PROG_MKDIR_P
  # Code from module sys_wait:
  gl_SYS_WAIT_H
  AC_PROG_MKDIR_P
  # Code from module tempname:
  gl_FUNC_GEN_TEMPNAME
  # Code from module termios:
  gl_TERMIOS_H
  # Code from module threadlib:
  gl_THREADLIB
  # Code from module time:
  gl_HEADER_TIME_H
  # Code from module time_r:
  gl_TIME_R
  gl_TIME_MODULE_INDICATOR([time_r])
  # Code from module timegm:
  gl_FUNC_TIMEGM
  gl_TIME_MODULE_INDICATOR([timegm])
  # Code from module uname:
  gl_FUNC_UNAME
  gl_SYS_UTSNAME_MODULE_INDICATOR([uname])
  # Code from module unistd:
  gl_UNISTD_H
  # Code from module useless-if-before-free:
  # Code from module usleep:
  gl_FUNC_USLEEP
  gl_UNISTD_MODULE_INDICATOR([usleep])
  # Code from module vasnprintf:
  gl_FUNC_VASNPRINTF
  # Code from module vasprintf:
  gl_FUNC_VASPRINTF
  gl_STDIO_MODULE_INDICATOR([vasprintf])
  m4_ifdef([AM_XGETTEXT_OPTION],
    [AM_][XGETTEXT_OPTION([--flag=asprintf:2:c-format])
     AM_][XGETTEXT_OPTION([--flag=vasprintf:2:c-format])])
  # Code from module vc-list-files:
  # Code from module verify:
  # Code from module waitpid:
  gl_FUNC_WAITPID
  gl_SYS_WAIT_MODULE_INDICATOR([waitpid])
  # Code from module warn-on-use:
  # Code from module wchar:
  gl_WCHAR_H
  # Code from module xsize:
  gl_XSIZE
  # End of code from modules
  m4_ifval(gl_LIBSOURCES_LIST, [
    m4_syscmd([test ! -d ]m4_defn([gl_LIBSOURCES_DIR])[ ||
      for gl_file in ]gl_LIBSOURCES_LIST[ ; do
        if test ! -r ]m4_defn([gl_LIBSOURCES_DIR])[/$gl_file ; then
          echo "missing file ]m4_defn([gl_LIBSOURCES_DIR])[/$gl_file" >&2
          exit 1
        fi
      done])dnl
      m4_if(m4_sysval, [0], [],
        [AC_FATAL([expected source file, required through AC_LIBSOURCES, not found])])
  ])
  m4_popdef([gl_LIBSOURCES_DIR])
  m4_popdef([gl_LIBSOURCES_LIST])
  m4_popdef([AC_LIBSOURCES])
  m4_popdef([AC_REPLACE_FUNCS])
  m4_popdef([AC_LIBOBJ])
  AC_CONFIG_COMMANDS_PRE([
    gl_libobjs=
    gl_ltlibobjs=
    if test -n "$gl_LIBOBJS"; then
      # Remove the extension.
      sed_drop_objext='s/\.o$//;s/\.obj$//'
      for i in `for i in $gl_LIBOBJS; do echo "$i"; done | sed -e "$sed_drop_objext" | sort | uniq`; do
        gl_libobjs="$gl_libobjs $i.$ac_objext"
        gl_ltlibobjs="$gl_ltlibobjs $i.lo"
      done
    fi
    AC_SUBST([gl_LIBOBJS], [$gl_libobjs])
    AC_SUBST([gl_LTLIBOBJS], [$gl_ltlibobjs])
  ])
  gltests_libdeps=
  gltests_ltlibdeps=
  m4_pushdef([AC_LIBOBJ], m4_defn([gltests_LIBOBJ]))
  m4_pushdef([AC_REPLACE_FUNCS], m4_defn([gltests_REPLACE_FUNCS]))
  m4_pushdef([AC_LIBSOURCES], m4_defn([gltests_LIBSOURCES]))
  m4_pushdef([gltests_LIBSOURCES_LIST], [])
  m4_pushdef([gltests_LIBSOURCES_DIR], [])
  gl_COMMON
  gl_source_base='gnulib/tests'
changequote(,)dnl
  gltests_WITNESS=IN_`echo "${PACKAGE-$PACKAGE_TARNAME}" | LC_ALL=C tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ | LC_ALL=C sed -e 's/[^A-Z0-9_]/_/g'`_GNULIB_TESTS
changequote([, ])dnl
  AC_SUBST([gltests_WITNESS])
  gl_module_indicator_condition=$gltests_WITNESS
  m4_pushdef([gl_MODULE_INDICATOR_CONDITION], [$gl_module_indicator_condition])
  AC_REQUIRE([gl_HEADER_SYS_SOCKET])
  if test "$ac_cv_header_winsock2_h" = yes; then
    AC_LIBOBJ([accept])
  fi
  gl_SYS_SOCKET_MODULE_INDICATOR([accept])
  AC_REQUIRE([gl_HEADER_SYS_SOCKET])
  if test "$ac_cv_header_winsock2_h" = yes; then
    AC_LIBOBJ([bind])
  fi
  gl_SYS_SOCKET_MODULE_INDICATOR([bind])
  AC_CHECK_FUNCS_ONCE([getegid])
  gl_ENVIRON
  gl_UNISTD_MODULE_INDICATOR([environ])
  gl_ERROR
  m4_ifdef([AM_XGETTEXT_OPTION],
    [AM_][XGETTEXT_OPTION([--flag=error:3:c-format])
     AM_][XGETTEXT_OPTION([--flag=error_at_line:5:c-format])])
  gl_FUNC_UNGETC_WORKS
  gl_FUNC_GETGROUPS
  gl_UNISTD_MODULE_INDICATOR([getgroups])
  gl_FUNC_GETPAGESIZE
  gl_UNISTD_MODULE_INDICATOR([getpagesize])
  gl_GETUGROUPS
  AC_C_BIGENDIAN
  AC_C_BIGENDIAN
  gl_INLINE
  AC_REQUIRE([gl_HEADER_SYS_SOCKET])
  if test "$ac_cv_header_winsock2_h" = yes; then
    AC_LIBOBJ([listen])
  fi
  gl_SYS_SOCKET_MODULE_INDICATOR([listen])
  dnl Check for prerequisites for memory fence checks.
  gl_FUNC_MMAP_ANON
  AC_CHECK_HEADERS_ONCE([sys/mman.h])
  AC_CHECK_FUNCS_ONCE([mprotect])
  gl_MGETGROUPS
  AC_CHECK_HEADERS_ONCE([unistd.h sys/wait.h])
  AC_CHECK_DECLS([program_invocation_name], [], [], [#include <errno.h>])
  AC_CHECK_DECLS([program_invocation_short_name], [], [], [#include <errno.h>])
  gl_FUNC_PUTENV
  gl_STDLIB_MODULE_INDICATOR([putenv])
  dnl Check for prerequisites for memory fence checks.
  gl_FUNC_MMAP_ANON
  AC_CHECK_HEADERS_ONCE([sys/mman.h])
  AC_CHECK_FUNCS_ONCE([mprotect])
  gl_FUNC_REALLOC_GNU
  gl_MODULE_INDICATOR([realloc-gnu])
  AC_CHECK_HEADERS_ONCE([sys/wait.h])
  AC_CHECK_DECLS_ONCE([alarm])
  gl_STAT_TIME
  gl_STAT_BIRTHTIME
  gt_TYPE_WCHAR_T
  gt_TYPE_WINT_T
  dnl Check for prerequisites for memory fence checks.
  gl_FUNC_MMAP_ANON
  AC_CHECK_HEADERS_ONCE([sys/mman.h])
  AC_CHECK_FUNCS_ONCE([mprotect])
  gl_FUNC_SYMLINK
  gl_UNISTD_MODULE_INDICATOR([symlink])
  AC_CHECK_FUNCS_ONCE([shutdown])
  gl_THREAD
  gl_FUNC_UNSETENV
  gl_STDLIB_MODULE_INDICATOR([unsetenv])
  abs_aux_dir=`cd "$ac_aux_dir"; pwd`
  AC_SUBST([abs_aux_dir])
  gl_FUNC_WRITE
  gl_UNISTD_MODULE_INDICATOR([write])
  gl_XALLOC
  gl_YIELD
  m4_popdef([gl_MODULE_INDICATOR_CONDITION])
  m4_ifval(gltests_LIBSOURCES_LIST, [
    m4_syscmd([test ! -d ]m4_defn([gltests_LIBSOURCES_DIR])[ ||
      for gl_file in ]gltests_LIBSOURCES_LIST[ ; do
        if test ! -r ]m4_defn([gltests_LIBSOURCES_DIR])[/$gl_file ; then
          echo "missing file ]m4_defn([gltests_LIBSOURCES_DIR])[/$gl_file" >&2
          exit 1
        fi
      done])dnl
      m4_if(m4_sysval, [0], [],
        [AC_FATAL([expected source file, required through AC_LIBSOURCES, not found])])
  ])
  m4_popdef([gltests_LIBSOURCES_DIR])
  m4_popdef([gltests_LIBSOURCES_LIST])
  m4_popdef([AC_LIBSOURCES])
  m4_popdef([AC_REPLACE_FUNCS])
  m4_popdef([AC_LIBOBJ])
  AC_CONFIG_COMMANDS_PRE([
    gltests_libobjs=
    gltests_ltlibobjs=
    if test -n "$gltests_LIBOBJS"; then
      # Remove the extension.
      sed_drop_objext='s/\.o$//;s/\.obj$//'
      for i in `for i in $gltests_LIBOBJS; do echo "$i"; done | sed -e "$sed_drop_objext" | sort | uniq`; do
        gltests_libobjs="$gltests_libobjs $i.$ac_objext"
        gltests_ltlibobjs="$gltests_ltlibobjs $i.lo"
      done
    fi
    AC_SUBST([gltests_LIBOBJS], [$gltests_libobjs])
    AC_SUBST([gltests_LTLIBOBJS], [$gltests_ltlibobjs])
  ])
  LIBTESTS_LIBDEPS="$gltests_libdeps"
  AC_SUBST([LIBTESTS_LIBDEPS])
])

# Like AC_LIBOBJ, except that the module name goes
# into gl_LIBOBJS instead of into LIBOBJS.
AC_DEFUN([gl_LIBOBJ], [
  AS_LITERAL_IF([$1], [gl_LIBSOURCES([$1.c])])dnl
  gl_LIBOBJS="$gl_LIBOBJS $1.$ac_objext"
])

# Like AC_REPLACE_FUNCS, except that the module name goes
# into gl_LIBOBJS instead of into LIBOBJS.
AC_DEFUN([gl_REPLACE_FUNCS], [
  m4_foreach_w([gl_NAME], [$1], [AC_LIBSOURCES(gl_NAME[.c])])dnl
  AC_CHECK_FUNCS([$1], , [gl_LIBOBJ($ac_func)])
])

# Like AC_LIBSOURCES, except the directory where the source file is
# expected is derived from the gnulib-tool parameterization,
# and alloca is special cased (for the alloca-opt module).
# We could also entirely rely on EXTRA_lib..._SOURCES.
AC_DEFUN([gl_LIBSOURCES], [
  m4_foreach([_gl_NAME], [$1], [
    m4_if(_gl_NAME, [alloca.c], [], [
      m4_define([gl_LIBSOURCES_DIR], [gnulib/lib])
      m4_append([gl_LIBSOURCES_LIST], _gl_NAME, [ ])
    ])
  ])
])

# Like AC_LIBOBJ, except that the module name goes
# into gltests_LIBOBJS instead of into LIBOBJS.
AC_DEFUN([gltests_LIBOBJ], [
  AS_LITERAL_IF([$1], [gltests_LIBSOURCES([$1.c])])dnl
  gltests_LIBOBJS="$gltests_LIBOBJS $1.$ac_objext"
])

# Like AC_REPLACE_FUNCS, except that the module name goes
# into gltests_LIBOBJS instead of into LIBOBJS.
AC_DEFUN([gltests_REPLACE_FUNCS], [
  m4_foreach_w([gl_NAME], [$1], [AC_LIBSOURCES(gl_NAME[.c])])dnl
  AC_CHECK_FUNCS([$1], , [gltests_LIBOBJ($ac_func)])
])

# Like AC_LIBSOURCES, except the directory where the source file is
# expected is derived from the gnulib-tool parameterization,
# and alloca is special cased (for the alloca-opt module).
# We could also entirely rely on EXTRA_lib..._SOURCES.
AC_DEFUN([gltests_LIBSOURCES], [
  m4_foreach([_gl_NAME], [$1], [
    m4_if(_gl_NAME, [alloca.c], [], [
      m4_define([gltests_LIBSOURCES_DIR], [gnulib/tests])
      m4_append([gltests_LIBSOURCES_LIST], _gl_NAME, [ ])
    ])
  ])
])

# This macro records the list of files which have been installed by
# gnulib-tool and may be removed by future gnulib-tool invocations.
AC_DEFUN([gl_FILE_LIST], [
  build-aux/arg-nonnull.h
  build-aux/c++defs.h
  build-aux/config.rpath
  build-aux/gitlog-to-changelog
  build-aux/mktempd
  build-aux/useless-if-before-free
  build-aux/vc-list-files
  build-aux/warn-on-use.h
  lib/alignof.h
  lib/alloca.c
  lib/alloca.in.h
  lib/areadlink.c
  lib/areadlink.h
  lib/arpa_inet.in.h
  lib/asnprintf.c
  lib/asprintf.c
  lib/base64.c
  lib/base64.h
  lib/basename-lgpl.c
  lib/c-ctype.c
  lib/c-ctype.h
  lib/canonicalize-lgpl.c
  lib/chown.c
  lib/close-hook.c
  lib/close-hook.h
  lib/close.c
  lib/connect.c
  lib/count-one-bits.h
  lib/dirname-lgpl.c
  lib/dirname.h
  lib/errno.in.h
  lib/fchown-stub.c
  lib/fclose.c
  lib/fcntl.in.h
  lib/float+.h
  lib/float.in.h
  lib/fseeko.c
  lib/gai_strerror.c
  lib/getaddrinfo.c
  lib/getdelim.c
  lib/gethostname.c
  lib/getline.c
  lib/getpass.c
  lib/getpass.h
  lib/gettext.h
  lib/gettimeofday.c
  lib/glthread/lock.c
  lib/glthread/lock.h
  lib/glthread/threadlib.c
  lib/ignore-value.h
  lib/inet_ntop.c
  lib/inet_pton.c
  lib/intprops.h
  lib/ioctl.c
  lib/lseek.c
  lib/lstat.c
  lib/malloc.c
  lib/malloca.c
  lib/malloca.h
  lib/malloca.valgrind
  lib/md5.c
  lib/md5.h
  lib/memchr.c
  lib/memchr.valgrind
  lib/mkstemp.c
  lib/mkstemps.c
  lib/mktime-internal.h
  lib/mktime.c
  lib/netdb.in.h
  lib/netinet_in.in.h
  lib/open.c
  lib/pathmax.h
  lib/perror.c
  lib/physmem.c
  lib/physmem.h
  lib/pipe.c
  lib/poll.c
  lib/poll.in.h
  lib/printf-args.c
  lib/printf-args.h
  lib/printf-parse.c
  lib/printf-parse.h
  lib/pthread.in.h
  lib/random_r.c
  lib/rawmemchr.c
  lib/rawmemchr.valgrind
  lib/readlink.c
  lib/realloc.c
  lib/recv.c
  lib/sched.in.h
  lib/select.c
  lib/send.c
  lib/setsockopt.c
  lib/sig-handler.h
  lib/sigaction.c
  lib/signal.in.h
  lib/sigprocmask.c
  lib/size_max.h
  lib/sleep.c
  lib/snprintf.c
  lib/socket.c
  lib/sockets.c
  lib/sockets.h
  lib/stat.c
  lib/stdbool.in.h
  lib/stddef.in.h
  lib/stdint.in.h
  lib/stdio-impl.h
  lib/stdio-write.c
  lib/stdio.in.h
  lib/stdlib.in.h
  lib/stpcpy.c
  lib/strcasecmp.c
  lib/strchrnul.c
  lib/strchrnul.valgrind
  lib/strdup.c
  lib/strerror.c
  lib/strerror_r.c
  lib/string.in.h
  lib/strings.in.h
  lib/stripslash.c
  lib/strncasecmp.c
  lib/strndup.c
  lib/strnlen.c
  lib/strptime.c
  lib/strsep.c
  lib/strtok_r.c
  lib/sys_ioctl.in.h
  lib/sys_select.in.h
  lib/sys_socket.in.h
  lib/sys_stat.in.h
  lib/sys_time.in.h
  lib/sys_utsname.in.h
  lib/sys_wait.in.h
  lib/tempname.c
  lib/tempname.h
  lib/termios.in.h
  lib/time.in.h
  lib/time_r.c
  lib/timegm.c
  lib/uname.c
  lib/unistd.in.h
  lib/usleep.c
  lib/vasnprintf.c
  lib/vasnprintf.h
  lib/vasprintf.c
  lib/verify.h
  lib/w32sock.h
  lib/waitpid.c
  lib/wchar.in.h
  lib/xsize.h
  m4/00gnulib.m4
  m4/alloca.m4
  m4/arpa_inet_h.m4
  m4/asm-underscore.m4
  m4/base64.m4
  m4/canonicalize.m4
  m4/chown.m4
  m4/close.m4
  m4/configmake.m4
  m4/count-one-bits.m4
  m4/dirname.m4
  m4/dos.m4
  m4/double-slash-root.m4
  m4/eealloc.m4
  m4/environ.m4
  m4/errno_h.m4
  m4/error.m4
  m4/extensions.m4
  m4/fclose.m4
  m4/fcntl-o.m4
  m4/fcntl_h.m4
  m4/float_h.m4
  m4/fseeko.m4
  m4/func.m4
  m4/getaddrinfo.m4
  m4/getdelim.m4
  m4/getgroups.m4
  m4/gethostname.m4
  m4/getline.m4
  m4/getpagesize.m4
  m4/getpass.m4
  m4/gettimeofday.m4
  m4/getugroups.m4
  m4/gnulib-common.m4
  m4/hostent.m4
  m4/include_next.m4
  m4/inet_ntop.m4
  m4/inet_pton.m4
  m4/inline.m4
  m4/intmax_t.m4
  m4/inttypes_h.m4
  m4/ioctl.m4
  m4/lib-ld.m4
  m4/lib-link.m4
  m4/lib-prefix.m4
  m4/lock.m4
  m4/longlong.m4
  m4/lseek.m4
  m4/lstat.m4
  m4/malloc.m4
  m4/malloca.m4
  m4/md5.m4
  m4/memchr.m4
  m4/mgetgroups.m4
  m4/mkstemp.m4
  m4/mkstemps.m4
  m4/mktime.m4
  m4/mmap-anon.m4
  m4/mode_t.m4
  m4/multiarch.m4
  m4/netdb_h.m4
  m4/netinet_in_h.m4
  m4/onceonly.m4
  m4/open.m4
  m4/pathmax.m4
  m4/perror.m4
  m4/physmem.m4
  m4/pipe.m4
  m4/poll.m4
  m4/poll_h.m4
  m4/posix-shell.m4
  m4/printf.m4
  m4/pthread.m4
  m4/putenv.m4
  m4/random_r.m4
  m4/rawmemchr.m4
  m4/readlink.m4
  m4/realloc.m4
  m4/sched_h.m4
  m4/select.m4
  m4/servent.m4
  m4/setenv.m4
  m4/sigaction.m4
  m4/signal_h.m4
  m4/signalblocking.m4
  m4/sigpipe.m4
  m4/size_max.m4
  m4/sleep.m4
  m4/snprintf.m4
  m4/socketlib.m4
  m4/sockets.m4
  m4/socklen.m4
  m4/sockpfaf.m4
  m4/ssize_t.m4
  m4/stat-time.m4
  m4/stat.m4
  m4/stdbool.m4
  m4/stddef_h.m4
  m4/stdint.m4
  m4/stdint_h.m4
  m4/stdio_h.m4
  m4/stdlib_h.m4
  m4/stpcpy.m4
  m4/strcase.m4
  m4/strchrnul.m4
  m4/strdup.m4
  m4/strerror.m4
  m4/strerror_r.m4
  m4/string_h.m4
  m4/strings_h.m4
  m4/strndup.m4
  m4/strnlen.m4
  m4/strptime.m4
  m4/strsep.m4
  m4/strtok_r.m4
  m4/symlink.m4
  m4/sys_ioctl_h.m4
  m4/sys_select_h.m4
  m4/sys_socket_h.m4
  m4/sys_stat_h.m4
  m4/sys_time_h.m4
  m4/sys_utsname_h.m4
  m4/sys_wait_h.m4
  m4/tempname.m4
  m4/termios_h.m4
  m4/thread.m4
  m4/threadlib.m4
  m4/time_h.m4
  m4/time_r.m4
  m4/timegm.m4
  m4/tm_gmtoff.m4
  m4/uname.m4
  m4/ungetc.m4
  m4/unistd_h.m4
  m4/usleep.m4
  m4/vasnprintf.m4
  m4/vasprintf.m4
  m4/waitpid.m4
  m4/warn-on-use.m4
  m4/wchar_h.m4
  m4/wchar_t.m4
  m4/wint_t.m4
  m4/write.m4
  m4/xalloc.m4
  m4/xsize.m4
  m4/yield.m4
  tests/init.sh
  tests/macros.h
  tests/nap.h
  tests/signature.h
  tests/test-alignof.c
  tests/test-alloca-opt.c
  tests/test-areadlink.c
  tests/test-areadlink.h
  tests/test-arpa_inet.c
  tests/test-base64.c
  tests/test-binary-io.c
  tests/test-binary-io.sh
  tests/test-c-ctype.c
  tests/test-canonicalize-lgpl.c
  tests/test-chown.c
  tests/test-chown.h
  tests/test-count-one-bits.c
  tests/test-environ.c
  tests/test-errno.c
  tests/test-fcntl-h.c
  tests/test-fseeko.c
  tests/test-fseeko.sh
  tests/test-fseeko2.sh
  tests/test-func.c
  tests/test-getaddrinfo.c
  tests/test-getdelim.c
  tests/test-getgroups.c
  tests/test-gethostname.c
  tests/test-getline.c
  tests/test-gettimeofday.c
  tests/test-ignore-value.c
  tests/test-inet_ntop.c
  tests/test-inet_pton.c
  tests/test-lock.c
  tests/test-lseek.c
  tests/test-lseek.sh
  tests/test-lstat.c
  tests/test-lstat.h
  tests/test-malloca.c
  tests/test-md5.c
  tests/test-memchr.c
  tests/test-netdb.c
  tests/test-netinet_in.c
  tests/test-open.c
  tests/test-open.h
  tests/test-perror.c
  tests/test-perror.sh
  tests/test-pipe.c
  tests/test-poll-h.c
  tests/test-poll.c
  tests/test-random_r.c
  tests/test-rawmemchr.c
  tests/test-readlink.c
  tests/test-readlink.h
  tests/test-realloc-gnu.c
  tests/test-sched.c
  tests/test-select-fd.c
  tests/test-select-in.sh
  tests/test-select-out.sh
  tests/test-select-stdin.c
  tests/test-select.c
  tests/test-sigaction.c
  tests/test-signal.c
  tests/test-sigpipe.c
  tests/test-sigpipe.sh
  tests/test-sleep.c
  tests/test-snprintf.c
  tests/test-sockets.c
  tests/test-stat-time.c
  tests/test-stat.c
  tests/test-stat.h
  tests/test-stdbool.c
  tests/test-stddef.c
  tests/test-stdint.c
  tests/test-stdio.c
  tests/test-stdlib.c
  tests/test-strchrnul.c
  tests/test-strerror.c
  tests/test-strerror_r.c
  tests/test-string.c
  tests/test-strings.c
  tests/test-strnlen.c
  tests/test-symlink.c
  tests/test-symlink.h
  tests/test-sys_ioctl.c
  tests/test-sys_select.c
  tests/test-sys_socket.c
  tests/test-sys_stat.c
  tests/test-sys_time.c
  tests/test-sys_utsname.c
  tests/test-sys_wait.c
  tests/test-sys_wait.h
  tests/test-termios.c
  tests/test-time.c
  tests/test-uname.c
  tests/test-unistd.c
  tests/test-unsetenv.c
  tests/test-usleep.c
  tests/test-vasnprintf.c
  tests/test-vasprintf.c
  tests/test-vc-list-files-cvs.sh
  tests/test-vc-list-files-git.sh
  tests/test-verify.c
  tests/test-verify.sh
  tests/test-wchar.c
  tests/test-xalloc-die.c
  tests/test-xalloc-die.sh
  tests/zerosize-ptr.h
  tests=lib/accept.c
  tests=lib/binary-io.h
  tests=lib/bind.c
  tests=lib/error.c
  tests=lib/error.h
  tests=lib/exitfail.c
  tests=lib/exitfail.h
  tests=lib/getgroups.c
  tests=lib/getpagesize.c
  tests=lib/getugroups.c
  tests=lib/getugroups.h
  tests=lib/glthread/thread.c
  tests=lib/glthread/thread.h
  tests=lib/glthread/yield.h
  tests=lib/listen.c
  tests=lib/mgetgroups.c
  tests=lib/mgetgroups.h
  tests=lib/progname.c
  tests=lib/progname.h
  tests=lib/putenv.c
  tests=lib/realloc.c
  tests=lib/same-inode.h
  tests=lib/stat-time.h
  tests=lib/symlink.c
  tests=lib/unsetenv.c
  tests=lib/w32sock.h
  tests=lib/write.c
  tests=lib/xalloc-die.c
  tests=lib/xalloc.h
  tests=lib/xmalloc.c
  top/GNUmakefile
  top/maint.mk
])
